
version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    env_file:
      - db.env
    volumes:
      - /c/Users/fabio/workspace/2003_tawny/ds_test/ds-playground/database-data:/var/lib/postgresql/data # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose